// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Account defines model for Account.
type Account struct {
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Email     openapi_types.Email `json:"email"`
	Id        string              `json:"id"`
	Meta      ResponseMeta        `json:"meta"`
	Name      *string             `json:"name,omitempty"`
}

// Cart defines model for Cart.
type Cart struct {
	Currency *string      `json:"currency,omitempty"`
	Id       string       `json:"id"`
	Items    []CartItem   `json:"items"`
	Meta     ResponseMeta `json:"meta"`
	Total    float32      `json:"total"`
}

// CartItem defines model for CartItem.
type CartItem struct {
	Price       float32 `json:"price"`
	ProductId   string  `json:"productId"`
	ProductName *string `json:"productName,omitempty"`
	Quantity    int     `json:"quantity"`
}

// Category defines model for Category.
type Category struct {
	Description  *string `json:"description,omitempty"`
	Id           string  `json:"id"`
	Name         string  `json:"name"`
	ProductCount *int    `json:"productCount,omitempty"`
	Slug         string  `json:"slug"`
}

// Error defines model for Error.
type Error struct {
	Error     string     `json:"error"`
	Message   string     `json:"message"`
	RequestId string     `json:"requestId"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// Health defines model for Health.
type Health struct {
	Instance  string    `json:"instance"`
	RequestId *string   `json:"requestId,omitempty"`
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
}

// Homepage defines model for Homepage.
type Homepage struct {
	Featured []Product    `json:"featured"`
	Meta     ResponseMeta `json:"meta"`
	Title    string       `json:"title"`
}

// Product defines model for Product.
type Product struct {
	CategoryId  *string   `json:"categoryId,omitempty"`
	Currency    *string   `json:"currency,omitempty"`
	Description *string   `json:"description,omitempty"`
	Id          string    `json:"id"`
	ImageUrl    *string   `json:"imageUrl,omitempty"`
	InStock     bool      `json:"inStock"`
	Name        string    `json:"name"`
	Price       float32   `json:"price"`
	Slug        string    `json:"slug"`
	Tags        *[]string `json:"tags,omitempty"`
}

// ProductUpdate defines model for ProductUpdate.
type ProductUpdate struct {
	Description *string  `json:"description,omitempty"`
	InStock     *bool    `json:"inStock,omitempty"`
	Name        *string  `json:"name,omitempty"`
	Price       *float32 `json:"price,omitempty"`
}

// ResponseMeta defines model for ResponseMeta.
type ResponseMeta struct {
	HeadersReceived *map[string]string `json:"headersReceived,omitempty"`
	Instance        string             `json:"instance"`
	RequestId       string             `json:"requestId"`
	Timestamp       time.Time          `json:"timestamp"`
}

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = ProductUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get homepage content
	// (GET /)
	GetHomepage(w http.ResponseWriter, r *http.Request)
	// Get user account info (non-cacheable)
	// (GET /account)
	GetAccount(w http.ResponseWriter, r *http.Request)
	// Update product (triggers cache purge)
	// (POST /admin/product/{id})
	UpdateProduct(w http.ResponseWriter, r *http.Request, id string)
	// Get user cart (non-cacheable)
	// (GET /cart)
	GetCart(w http.ResponseWriter, r *http.Request)
	// List all product categories
	// (GET /category)
	ListCategories(w http.ResponseWriter, r *http.Request)
	// Health check endpoint
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Get product details
	// (GET /product/{id})
	GetProduct(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get homepage content
// (GET /)
func (_ Unimplemented) GetHomepage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user account info (non-cacheable)
// (GET /account)
func (_ Unimplemented) GetAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update product (triggers cache purge)
// (POST /admin/product/{id})
func (_ Unimplemented) UpdateProduct(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user cart (non-cacheable)
// (GET /cart)
func (_ Unimplemented) GetCart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all product categories
// (GET /category)
func (_ Unimplemented) ListCategories(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check endpoint
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get product details
// (GET /product/{id})
func (_ Unimplemented) GetProduct(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHomepage operation middleware
func (siw *ServerInterfaceWrapper) GetHomepage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHomepage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProduct operation middleware
func (siw *ServerInterfaceWrapper) UpdateProduct(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProduct(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCart operation middleware
func (siw *ServerInterfaceWrapper) GetCart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCategories(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProduct operation middleware
func (siw *ServerInterfaceWrapper) GetProduct(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProduct(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/", wrapper.GetHomepage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/account", wrapper.GetAccount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/product/{id}", wrapper.UpdateProduct)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cart", wrapper.GetCart)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/category", wrapper.ListCategories)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/product/{id}", wrapper.GetProduct)
	})

	return r
}
