services:
  api:
    build:
      context: ./apps/api
    environment:
      - INSTANCE_NAME=local-dev

  varnish:
    build:
      context: ./apps/varnish
    ports:
      - "8080:80"
    depends_on:
      - api
